import os

DB_CONNECTION_STRING = os.getenv('DB_CONNECTION_STRING') 
FINGRID_CONSUMPTION_API_KEY = os.getenv('FINGRID_CONSUMPTION_API_KEY') 
FINGRID_PRODUCTION_API_KEY = os.getenv('FINGRID_PRODUCTION_API_KEY') 

